package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        script {
            name = "Install"
            scriptContent = "npm install"
        }
        script {
            name = "run build"
            scriptContent = "npm run build"
        }
        script {
            name = "run phantom test"
            scriptContent = "npm run test-phantomjs"
        }
        script {
            name = "deploy"
            scriptContent = "cp -rf %system.teamcity.build.workingDir%/dist/my-dream-app/ /Users/gosivasa/appdy/teamcity-study/my-dream-app/deploy/"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            name = "Install step"
            scriptContent = "npm insta"
        }
    }
}
